# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkFun <- function(residuals, tau) {
    .Call(`_quantGA_checkFun`, residuals, tau)
}

objFun <- function(beta, X, y, tau) {
    .Call(`_quantGA_objFun`, beta, X, y, tau)
}

popFitness <- function(pop, X, y, tau) {
    .Call(`_quantGA_popFitness`, pop, X, y, tau)
}

